### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by ozanbayram** [software-mansion/starknet.py#1068]
### What happened

I want to call `allowance(owner, spender)` from StarkGate: ETH Token, StarkGate: USDC Token and StarkGate: USDT Token 
contract. StarkGate: ETH Token contract it works but StarkGate: USDC Token and StarkGate: USDT Token
 contract returns `starknet_py.net.client_errors.ClientError: Client failed with code 20: Contract not found.` 

StarkGate: ETH Token: 0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7
StarkGate: USDC Token: 0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8
StarkGate: USDT Token: 0x068f5c6a61780768455de69077e07e89787839bf8166decfbf92b645209c0fb8

### Stack trace

```
Traceback (most recent call last):
  File "/home/ozan/starkrevoke/approve_check.py", line 30, in <module>
    a=Approval().allowance(0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8,
  File "/home/ozan/starkrevoke/approve_check.py", line 23, in allowance
    contract_call = Contract.from_address_sync(address=contract, provider=self.provider, proxy_config=True)
  File "/home/ozan/.local/lib/python3.8/site-packages/starknet_py/utils/sync/sync.py", line 15, in impl
    return sync_fun(*args, **kwargs)
  File "/home/ozan/.local/lib/python3.8/site-packages/asgiref/sync.py", line 277, in __call__
    return call_result.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/ozan/.local/lib/python3.8/site-packages/asgiref/sync.py", line 353, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/ozan/.local/lib/python3.8/site-packages/starknet_py/contract.py", line 523, in from_address
    abi = await ContractAbiResolver(
  File "/home/ozan/.local/lib/python3.8/site-packages/starknet_py/proxy/contract_abi_resolver.py", line 86, in resolve
    return await self.resolve_abi()
  File "/home/ozan/.local/lib/python3.8/site-packages/starknet_py/proxy/contract_abi_resolver.py", line 140, in resolve_abi
    raise err
  File "/home/ozan/.local/lib/python3.8/site-packages/starknet_py/proxy/contract_abi_resolver.py", line 121, in resolve_abi
    contract_class = await _get_class_at(
  File "/home/ozan/.local/lib/python3.8/site-packages/starknet_py/proxy/contract_abi_resolver.py", line 215, in _get_class_at
    raise err
  File "/home/ozan/.local/lib/python3.8/site-packages/starknet_py/proxy/contract_abi_resolver.py", line 207, in _get_class_at
    contract_class_hash = await client.get_class_hash_at(contract_address=address)
  File "/home/ozan/.local/lib/python3.8/site-packages/starknet_py/net/full_node_client.py", line 379, in get_class_hash_at
    res = await self._client.call(
  File "/home/ozan/.local/lib/python3.8/site-packages/starknet_py/net/http_client.py", line 101, in call
    self.handle_rpc_error(result)
  File "/home/ozan/.local/lib/python3.8/site-packages/starknet_py/net/http_client.py", line 108, in handle_rpc_error
    raise ClientError(
starknet_py.net.client_errors.ClientError: Client failed with code 20: Contract not found.
```

### Steps to reproduce

```
from starknet_py.net.full_node_client import FullNodeClient
from starknet_py.contract import Contract
from starknet_py.net.account.account import Account
from starknet_py.net.models import StarknetChainId
from starknet_py.net.signer.stark_curve_signer import StarkCurveSigner


class Approval():
    def __init__(self):
        node_url = "https://starknet-mainnet.public.blastapi.io"
        full_node_client = FullNodeClient(node_url=node_url)
        self.provider=Account(
            address=0x02c0c89bec631039bcfc6f5041825baaae37f3f2606ce0d056c65093dd644b1a,
            signer= StarkCurveSigner,
            client=full_node_client,
            chain=StarknetChainId.MAINNET,
                            )
    def allowance(self, contract, owner, spender, kind):
        if kind == "nft":
            func = "isApprovedForAll"
        else :
            func = "allowance"
        contract_call = Contract.from_address_sync(address=contract, provider=self.provider, proxy_config=True)
        contract_call = contract_call.functions[func].prepare(owner, spender).call_sync()
        allowance = int(contract_call.as_tuple()[0])
        return allowance


if __name__ == "__main__":     
    a=Approval().allowance(0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8,
                       0x10055337e225d8461b0d5baca28942bf1d6089f1870a6fbf03313875b51db50,
                       0x7a6f98c03379b9513ca84cca1373ff452a7462a3b61598f0af5bb27ad7f76d1,
                       "token")
    print(a)

```

### SDK Version

Version: 0.16.1

### Python version

3.8.10

### What operating system are you using?

Linux

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by drknzz** [comment]
Hey, seems like the 2 contracts you provided (`USDC` and `USDT`) are not behind a proxy, unlike the `ETH` contract.

To create a `Contract` instance for them using `.from_address`, make sure to pass `proxy_config=False`, or don't specify the parameter, as the default value for proxy_config is `False`.

**Comment by drknzz** [comment]
If you do not know, whether a contract is behind a proxy or not during runtime, you could try fetching the contract with `proxy_config=True`, and if it was to fail (try + except), create the contract without passing `proxy_config`.

**Comment by ozanbayram** [comment]
> If you do not know, whether a contract is behind a proxy or not during runtime, you could try fetching the contract with `proxy_config=True`, and if it was to fail (try + except), create the contract without passing `proxy_config`.

Yes I will but still same for now.  `proxy_config=False` doesn't work

**Comment by drknzz** [comment]
I've checked, the code below works for me.

```
    USDC_ADDRESS = 0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8

    node_url = "https://starknet-mainnet.public.blastapi.io"
    full_node_client = FullNodeClient(node_url=node_url)

    provider = Account(
        address=0x123,
        key_pair=KeyPair.from_private_key(0x123),
        client=full_node_client,
        chain=StarknetChainId.MAINNET,
    )

    contract = Contract.from_address_sync(address=USDC_ADDRESS, provider=provider)
   ```
   
   Let me know if it does for you.

**Comment by ozanbayram** [comment]
> Hmm, did you create the StarkCurveSigner instance yourself somewhere, or are you passing the class object here?
> 
> ```
>         self.provider=Account(
>             address=0x02c0c89bec631039bcfc6f5041825baaae37f3f2606ce0d056c65093dd644b1a,
>             signer= StarkCurveSigner,
>             client=full_node_client,
>             chain=StarknetChainId.MAINNET,
>                             )
> ```

Firsly, `proxy_config=False` returns 
```
Traceback (most recent call last):
  File "/home/ozan/starkrevoke/approve_check.py", line 39, in <module>
    a=Approval().allowance(0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8,
  File "/home/ozan/starkrevoke/approve_check.py", line 24, in allowance
    contract_call = contract_call.functions[func].prepare(owner, spender).call_sync()
KeyError: 'allowance'
``` insteaf of `starknet_py.net.client_errors.ClientError: Client failed with code 20: Contract not found`
My mistake.

**Comment by drknzz** [comment]
Oh, okay; the 2 contracts are actually behind a proxy (sorry, my bad 🙊)

The difference between them and the ETH contract is that `implementation()` for ETH contract returns the **address** of the implementation and **class_hash** for USDC and USDC contracts.

It would be hard for us to support every type of possible proxy, so we support only the main ones, like OpenZeppelin's, Argent's or the ETH contract's proxy.

What you could do is create your own class that would know how to resolve the proxy of USDC and USDT contracts.
The instructions for that are in the [documentation](https://starknetpy.readthedocs.io/en/latest/guide/resolving_proxy_contracts.html#proxychecks).

**Comment by ozanbayram** [comment]
``

> I've checked, the code below works for me.
> 
> ```
>     USDC_ADDRESS = 0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8
> 
>     node_url = "https://starknet-mainnet.public.blastapi.io"
>     full_node_client = FullNodeClient(node_url=node_url)
> 
>     provider = Account(
>         address=0x123,
>         key_pair=KeyPair.from_private_key(0x123),
>         client=full_node_client,
>         chain=StarknetChainId.MAINNET,
>     )
> 
>     contract = Contract.from_address_sync(address=USDC_ADDRESS, provider=provider)
> ```
> 
> Let me know if it does for you.

```
from starknet_py.net.full_node_client import FullNodeClient
from starknet_py.contract import Contract
from starknet_py.net.account.account import Account
from starknet_py.net.models import StarknetChainId
from starknet_py.net.signer.stark_curve_signer import StarkCurveSigner, KeyPair

USDC_ADDRESS = 0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8
node_url = "https://starknet-mainnet.public.blastapi.io"
full_node_client = FullNodeClient(node_url=node_url)
provider = Account(
        address=0x123,
        key_pair=KeyPair.from_private_key(0x123),
        client=full_node_client,
        chain=StarknetChainId.MAINNET,
    )
contract = Contract.from_address_sync(address=USDC_ADDRESS, provider=provider)
contract.functions["allowance"].prepare(0x10055337e225d8461b0d5baca28942bf1d6089f1870a6fbf03313875b51db50, 0x7a6f98c03379b9513ca84cca1373ff452a7462a3b61598f0af5bb27ad7f76d1).call_sync()
```
returns 
```
Traceback (most recent call last):
  File "/home/ozan/starkrevoke/sw.py", line 17, in <module>
    contract.functions["allowance"].prepare(0x10055337e225d8461b0d5baca28942bf1d6089f1870a6fbf03313875b51db50, 0x7a6f98c03379b9513ca84cca1373ff452a7462a3b61598f0af5bb27ad7f76d1).call_sync()
KeyError: 'allowance'
```

**Comment by drknzz** [comment]
Let me know if there are still any problems.

**Comment by ozanbayram** [comment]
> Let me know if there are still any problems.

It works. But I have many contracts(NFTs, usdt, wbtc etc.) in database. Even more will be added. Starknet will have many contracts. how do i solve this?

**Comment by drknzz** [comment]
> It works. But I have many contracts(NFTs, usdt, wbtc etc.) in database. Even more will be added. Starknet will have many contracts. how do i solve this?

You would need to pass ProxyChecks for the contracts that you want to resolve.

You can also pass some of the [already implemented ones](https://github.com/software-mansion/starknet.py/blob/b5de0d83d97d27241226e7268262766ef9939b32/starknet_py/proxy/proxy_check.py).

It might happen that some of the contracts you want to resolve use the same proxy pattern (like for USDC and USDT for example), so most likely you won't be needing to write many specific ProxyChecks.

```
proxy_config={"proxy_checks": [USDCProxyCheck(), SomeOtherProxyCheck(), EthProxyCheck(), WBTCProxyCheck(), ArgentProxyCheck()]}
```

`Contract.from_address `will try to resolve the proxy of a contract using the passed checks, one after another.
