### ISSUE TITLE
[BUG] estimateFee RPC call failed with FullNodeClient

### ISSUE THREAD

**Issue by asluchevskiy** [software-mansion/starknet.py#1100]
### What happened

When using Infura RPC, I can't estimate transaction fee

```
        calls = [approve_prepared_tx, swap_prepared_tx]
        invoke = self.account.sign_invoke_transaction_sync(calls=calls, auto_estimate=True)
        return self.account.client.send_transaction_sync(invoke)
```

### Stack trace

```
Traceback (most recent call last):
  File "/home/arceny/Dropbox/develop/starknet_project/starknet_project/gui.py", line 102, in run
    self.trader.run(projects=projects, wallet_delay=wallet_delay,
  File "/home/arceny/Dropbox/develop/starknet_project/starknet_project/starknet_trader.py", line 233, in run
    self.swap(swap_cls=project['cls'], account=account.starknet_account,
  File "/home/arceny/Dropbox/develop/starknet_project/starknet_project/starknet_trader.py", line 402, in swap
    res = s.swap(amount=amount, token_a_address=token_a_address, token_b_address=token_b_address,
  File "/home/arceny/Dropbox/develop/starknet_project/starknet_project/starknet_swap.py", line 168, in swap
    invoke = self.account.sign_invoke_transaction_sync(calls=calls, auto_estimate=True)
  File "/home/arceny/develop/starknet_project/venv/lib/python3.8/site-packages/starknet_py/utils/sync/sync.py", line 15, in impl
    return sync_fun(*args, **kwargs)
  File "/home/arceny/develop/starknet_project/venv/lib/python3.8/site-packages/asgiref/sync.py", line 277, in __call__
    return call_result.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/arceny/develop/starknet_project/venv/lib/python3.8/site-packages/asgiref/sync.py", line 353, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/arceny/develop/starknet_project/venv/lib/python3.8/site-packages/starknet_py/net/account/account.py", line 250, in sign_invoke_transaction
    execute_tx = await self._prepare_invoke(
  File "/home/arceny/develop/starknet_project/venv/lib/python3.8/site-packages/starknet_py/net/account/account.py", line 166, in _prepare_invoke
    max_fee = await self._get_max_fee(transaction, max_fee, auto_estimate)
  File "/home/arceny/develop/starknet_project/venv/lib/python3.8/site-packages/starknet_py/net/account/account.py", line 123, in _get_max_fee
    estimated_fee = await self._estimate_fee(transaction)
  File "/home/arceny/develop/starknet_project/venv/lib/python3.8/site-packages/starknet_py/net/account/account.py", line 184, in _estimate_fee
    estimated_fee = await self._client.estimate_fee(
  File "/home/arceny/Dropbox/develop/starknet_project/starknet_project/starknet.py", line 128, in estimate_fee
    res = await self._client.call(
  File "/home/arceny/develop/starknet_project/venv/lib/python3.8/site-packages/starknet_py/net/http_client.py", line 101, in call
    self.handle_rpc_error(result)
  File "/home/arceny/develop/starknet_project/venv/lib/python3.8/site-packages/starknet_py/net/http_client.py", line 108, in handle_rpc_error
    raise ClientError(
starknet_py.net.client_errors.ClientError: Client failed with code -32602: invalid type: map, expected a sequence at line 1 column 32.

```

### Steps to reproduce

1. Use infura starknet RPC
2. Use FullNodeClient()
3. Use account.sign_invoke_transaction_sync() method

### SDK Version

0.16.1

### Python version

3.11.3

### What operating system are you using?

Linux

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by asluchevskiy** [comment]
Update: using GatewayClient the same code works correctly

**Comment by drknzz** [comment]
Hey, thanks for the open issue.
Have you tried using [the latest version](https://github.com/software-mansion/starknet.py/releases/tag/v0.17.0-alpha)?

**Comment by asluchevskiy** [comment]
> Hey, thanks for the open issue. Have you tried using [the latest version](https://github.com/software-mansion/starknet.py/releases/tag/v0.17.0-alpha)?

Yes, I have the same error
`Client failed with code -32602: invalid type: map, expected a sequence at line 1 column 32.`

**Comment by drknzz** [comment]
@asluchevskiy
Hey, do you, by any chance, know which version of the RPC is used by your node? Is it v0.2 or v0.3?

**Comment by asluchevskiy** [comment]
@drknzz 
It is standart https://infura.io/ RPC, is there are any method to check it?

**Comment by drknzz** [comment]
Is there a v2/ or v3/ in the link you re using perhaps?

**Comment by asluchevskiy** [comment]
> Is there a v2/ or v3/ in the link you re using perhaps?

https://starknet-mainnet.infura.io/v3/api_key

So it is v3

**Comment by Dav17d** [comment]
Same for me

**Comment by asluchevskiy** [comment]
Bump, still actual with the latest version of starknet.py

**Comment by ddoktorski** [comment]
Hi @asluchevskiy Can you provide more information about calls `approve_prepared_tx` and `swap_prepared_tx`?

**Comment by ddoktorski** [comment]
@asluchevskiy 
Since there hasn't been a response for some time, I will be closing this issue. If you're still encountering this problem in the latest version, please don't hesitate to reopen it with updated details.
