### ISSUE TITLE
[BUG] Account setup error

### ISSUE THREAD

**Issue by Rainbow1nTheDark** [software-mansion/starknet.py#1148]
### What happened

Python cannot load LoadLibraryEx library at from starknet_py.net.account.account import Account.

I tried to reinstall and update packages and also tried to use a different laptop.

### Stack trace

Traceback (most recent call last):
  File "c:\Users\hai1r\OneDrive\Documents\scripts\starknet\starknet.py", line 8, in <module>
    from starknet_py.net.account.account import Account
  File "C:\Users\hai1r\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starknet_py\net\account\account.py", line 9, in <module>
    from starknet_py.hash.address import compute_address
  File "C:\Users\hai1r\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starknet_py\hash\address.py", line 4, in <module>
    from starknet_py.hash.utils import compute_hash_on_elements
  File "C:\Users\hai1r\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starknet_py\hash\utils.py", line 5, in <module>
    from crypto_cpp_py.cpp_bindings import (
  File "C:\Users\hai1r\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\crypto_cpp_py\cpp_bindings.py", line 96, in <module>
    def cpp_hash(left: int, right: int) -> int:
  File "C:\Users\hai1r\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\crypto_cpp_py\cpp_bindings.py", line 48, in load_cpp_lib
    CPP_LIB_BINDING = load_cpp_lib_windows(cpp_lib_file)
  File "C:\Users\hai1r\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\crypto_cpp_py\cpp_bindings.py", line 58, in load_cpp_lib_windows
    dll_handle = win32api.LoadLibraryEx(dll_name, 0, handle1)
pywintypes.error: (126, 'LoadLibraryEx', 'The specified module could not be found.')

### Steps to reproduce

client = FullNodeClient(node_url=RPC_STARK)
    account = Account(
            client=client,
            address=RPC_STARK,
            key_pair=key_pair,
            chain=StarknetChainId.TESTNET,
        )

print(account.get_balance())

### SDK Version

-

### Python version

3.10

### What operating system are you using?

Windows

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by tomek0123456789** [comment]
Hi, are you trying to install MinGW as in our docs via chocolatey? If so and the problem persists, we've answered to such problems on starknet.py channel on Starknet Discord (link in docs).

**Comment by Rainbow1nTheDark** [comment]
Hi, yes, I have MinGW installed via choco and I also have the PATH updated. I still have the same issue.

**Comment by tomek0123456789** [comment]
You can take a look at our discord channel, exactly [this message](https://discord.com/channels/793094838509764618/1138803218571345930/1138804757100777592), where we answered problems similar to yours

**Comment by NeedWings** [comment]
try to put files libcrypto_c_exports.dll libgcc_s_seh-1.dll libstdc++-6.dll libwinpthread-1.dll in same folder as your main script.
If it won't help, then reinstall python
