### ISSUE TITLE
Unnecessary named arguments provided: 'path_len'.

### ISSUE THREAD

**Issue by zmctinas** [software-mansion/starknet.py#1151]
### What happened

JediSwap: AMM swap  contract address: 0x041fd22b238fa21cfcf5dd45a8548974d8263b3a531a60388411c5e230f97023
when i use Contract to fetch estimate fee i got errors: 
starknet_py.serialization.errors.InvalidTypeException: Unnecessary named arguments provided: 'path_len'.
my code:
```python
contract = Contract(
    address="0x041fd22b238fa21cfcf5dd45a8548974d8263b3a531a60388411c5e230f97023",
    abi=jediswap_abi,
    provider=account
)

est_fee = contract.functions["swap_exact_tokens_for_tokens"].prepare(
    amountIn="1000000000000000",
    amountOutMin="1758213",
    path_len=0x2,
    path=[
        "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7",
        "0x53c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8"
    ],
    to="0x2e696f7fd40f006c9719c405d4138098c71366a4a7b4768bc878327b13a11b6",
    deadline="1692258166"
).estimate_fee_sync()
```

### Stack trace

Traceback (most recent call last):
  File "/Users/xiaoweiwang/Documents/python/bl-batch-operations/test_starknet.py", line 811, in <module>
    est_fee = contract.functions["swap_exact_tokens_for_tokens"].prepare(
  File "/Users/xiaoweiwang/.local/share/virtualenvs/bl-batch-operations-5D3lKCYn/lib/python3.9/site-packages/starknet_py/contract.py", line 463, in prepare
    calldata = self._payload_transformer.serialize(*args, **kwargs)
  File "/Users/xiaoweiwang/.local/share/virtualenvs/bl-batch-operations-5D3lKCYn/lib/python3.9/site-packages/starknet_py/serialization/function_serialization_adapter.py", line 37, in serialize
    named_arguments = self._merge_arguments(args, kwargs)
  File "/Users/xiaoweiwang/.local/share/virtualenvs/bl-batch-operations-5D3lKCYn/lib/python3.9/site-packages/starknet_py/serialization/function_serialization_adapter.py", line 70, in _merge_arguments
    self._ensure_no_unnecessary_args(expected_args, provided_args)
  File "/Users/xiaoweiwang/.local/share/virtualenvs/bl-batch-operations-5D3lKCYn/lib/python3.9/site-packages/starknet_py/serialization/function_serialization_adapter.py", line 87, in _ensure_no_unnecessary_args
    raise InvalidTypeException(
starknet_py.serialization.errors.InvalidTypeException: Unnecessary named arguments provided: 'path_len'.

### Steps to reproduce

1. python3 xx.py

### SDK Version

starknet-py==0.17.1

### Python version

Python 3.9.16

### What operating system are you using?

Mac

### Is there an existing issue for this?

- [ ] I have searched the existing issues and verified no issue exits for this problem.

**Comment by tomek0123456789** [comment]
Hi, it seems that you don't need to pass `path_len` argument to the `prepare` method, please try that and if that problem persists, let us know!

**Comment by zmctinas** [comment]
> 您好，看来您不需要`path_len`向该`prepare`方法传递参数，请尝试一下，如果问题仍然存在，请告诉我们！

thx,very much
