### ISSUE TITLE
Got en exception while executing transfer function

### ISSUE THREAD

**Issue by zmctinas** [software-mansion/starknet.py#1181]
### What happened

When my wallet address is updated to `cairo 1`, I get an error when I execute the `transfer` function
my code:
```python
transfer_prepare = contract.functions["transfer"].prepare(
    recipient=int(to, 16),
    amount=amount
)
approve_est_fee = transfer_prepare.estimate_fee_sync()
overall_fee = approve_est_fee.overall_fee
resp = account.execute_sync([transfer_prepare], max_fee=int(overall_fee * 2))
print(f'resp = {hex(resp.transaction_hash)}')
```
How can i fix it

### Stack trace

Traceback (most recent call last):
  File "/Users/xiaoweiwang/Documents/python/bl-batch-operations/test_bridge.py", line 38, in <module>
    js.starknet_transfer(wallet_address, pk, to_adr, '0.2', Coin.BASE)
  File "/Users/xiaoweiwang/Documents/python/bl-batch-operations/scripts/swap_module/jediswap.py", line 926, in starknet_transfer
    transfer_prepare, overall_fee = self.starknet_transfer_call(account, token, to_adr, amount)
  File "/Users/xiaoweiwang/Documents/python/bl-batch-operations/scripts/swap_module/jediswap.py", line 909, in starknet_transfer_call
    approve_est_fee = transfer_prepare.estimate_fee_sync()
  File "/Users/xiaoweiwang/.local/share/virtualenvs/bl-batch-operations-5D3lKCYn/lib/python3.9/site-packages/starknet_py/utils/sync/sync.py", line 15, in impl
    return sync_fun(*args, **kwargs)
  File "/Users/xiaoweiwang/.local/share/virtualenvs/bl-batch-operations-5D3lKCYn/lib/python3.9/site-packages/asgiref/sync.py", line 277, in __call__
    return call_result.result()
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/xiaoweiwang/.local/share/virtualenvs/bl-batch-operations-5D3lKCYn/lib/python3.9/site-packages/asgiref/sync.py", line 353, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/Users/xiaoweiwang/.local/share/virtualenvs/bl-batch-operations-5D3lKCYn/lib/python3.9/site-packages/starknet_py/contract.py", line 397, in estimate_fee
    estimated_fee = await self._client.estimate_fee(
  File "/Users/xiaoweiwang/.local/share/virtualenvs/bl-batch-operations-5D3lKCYn/lib/python3.9/site-packages/starknet_py/net/full_node_client.py", line 347, in estimate_fee
    res = await self._client.call(
  File "/Users/xiaoweiwang/Documents/python/bl-batch-operations/scripts/addition_module/starknet_http_client_custom.py", line 94, in call
    self.handle_rpc_error(result)
  File "/Users/xiaoweiwang/Documents/python/bl-batch-operations/scripts/addition_module/starknet_http_client_custom.py", line 101, in handle_rpc_error
    raise ClientError(
starknet_py.net.client_errors.ClientError: Client failed with code -32603: Internal error: StarknetErrorCode.TRANSACTION_FAILED: Execution was reverted; failure reason: [0x496e70757420746f6f206c6f6e6720666f7220617267756d656e7473]..

### Steps to reproduce

1. call transfer function

### SDK Version

0.18.1

### Python version

3.9.16

### What operating system are you using?

Linux, Mac

### Is there an existing issue for this?

- [ ] I have searched the existing issues and verified no issue exits for this problem.

**Comment by EvolveArt** [comment]
You're having an `Input too long for arguments` error as specified at the end of the error message. Please send which contract you are trying to interact with to help debugging.

**Comment by tomek0123456789** [comment]
Hi, sending transactions in Cairo1 will be addressed in the next starknet.py release, stay tuned!

**Comment by tomek0123456789** [comment]
@zmctinas, you should be able to run your code with the latest version of `starknet.py` now without any issues. If any problem occurs, please let us know here.
