### ISSUE TITLE
pip3 install emitted error

### ISSUE THREAD

**Issue by www5226448** [software-mansion/starknet.py#407]
my environment:
Mac M1 , mac Os 11.2.3 (20D91)
python 3.9

Building wheel for crypto-cpp-py (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [102 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      Crosscompiling enabled
      Targeting universal2-apple-macos10.9
      cmake_minimum_required (VERSION 3.5)
      if (NOT DEFINED CMAKE_CXX_COMPILER)
        set(CMAKE_CXX_COMPILER /usr/bin/clang++)
      endif()
      
      project(StarkwareCryptoLib VERSION 0.1.0 LANGUAGES CXX)
      
      set(CMAKE_CXX_STANDARD 17)
      
      include(FetchContent)
      FetchContent_Declare(
        googletest
        URL https://github.com/google/googletest/archive/609281088cfefc76f9d0ce82e1ff6c30cc3591e5.zip
      )
      # For Windows: Prevent overriding the parent project's compiler/linker settings
      set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
      FetchContent_MakeAvailable(googletest)
      
      include(CTest)
      enable_testing()
      include_directories("${CMAKE_SOURCE_DIR}/src")
      
      if (NOT DEFINED CMAKE_BUILD_TYPE)
        set(CMAKE_BUILD_TYPE Debug)
      endif()
      
      set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
      set(CMAKE_CXX_FLAGS "-std=c++17 -Werror -Wall -Wextra -fno-strict-aliasing -fPIC ${CMAKE_CXX_FLAGS} -target universal2-apple-macos10.9")
      
      set(CC_OPTIMIZE "-O3")
      
      set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -g")
      set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${CC_OPTIMIZE}")
      
      add_subdirectory(src)
      ./build_extension.sh: line 34: cmake: command not found
      sed: build/Release/_deps/googletest-src/CMakeLists.txt: No such file or directory
      make: *** No targets specified and no makefile found.  Stop.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/tmp/pip-install-d0hmj2lg/crypto-cpp-py_3ab0c761eaac4561af1b22ca8e1c1aac/setup.py", line 48, in <module>
          setup(
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/private/tmp/pip-install-d0hmj2lg/crypto-cpp-py_3ab0c761eaac4561af1b22ca8e1c1aac/setup.py", line 16, in run
          self.run_command("build_ext")
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
          _build_ext.build_ext.build_extensions(self)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/tmp/pip-install-d0hmj2lg/crypto-cpp-py_3ab0c761eaac4561af1b22ca8e1c1aac/setup.py", line 30, in build_extension
          subprocess.run(
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 524, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command './build_extension.sh' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for crypto-cpp-py
  Running setup.py clean for crypto-cpp-py
Successfully built starknet.py
Failed to build crypto-cpp-py
Installing collected packages: crypto-cpp-py, starknet.py
  Running setup.py install for crypto-cpp-py ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for crypto-cpp-py did not run successfully.
  │ exit code: 1
  ╰─> [106 lines of output]
      running install
      /Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running build_ext
      Crosscompiling enabled
      Targeting universal2-apple-macos10.9
      cmake_minimum_required (VERSION 3.5)
      if (NOT DEFINED CMAKE_CXX_COMPILER)
        set(CMAKE_CXX_COMPILER /usr/bin/clang++)
      endif()
      
      project(StarkwareCryptoLib VERSION 0.1.0 LANGUAGES CXX)
      
      set(CMAKE_CXX_STANDARD 17)
      
      include(FetchContent)
      FetchContent_Declare(
        googletest
        URL https://github.com/google/googletest/archive/609281088cfefc76f9d0ce82e1ff6c30cc3591e5.zip
      )
      # For Windows: Prevent overriding the parent project's compiler/linker settings
      set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
      FetchContent_MakeAvailable(googletest)
      
      include(CTest)
      enable_testing()
      include_directories("${CMAKE_SOURCE_DIR}/src")
      
      if (NOT DEFINED CMAKE_BUILD_TYPE)
        set(CMAKE_BUILD_TYPE Debug)
      endif()
      
      set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
      set(CMAKE_CXX_FLAGS "-std=c++17 -Werror -Wall -Wextra -fno-strict-aliasing -fPIC ${CMAKE_CXX_FLAGS} -target universal2-apple-macos10.9")
      
      set(CC_OPTIMIZE "-O3")
      
      set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -g")
      set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${CC_OPTIMIZE}")
      
      add_subdirectory(src)
      ./build_extension.sh: line 34: cmake: command not found
      sed: build/Release/_deps/googletest-src/CMakeLists.txt: No such file or directory
      make: *** No targets specified and no makefile found.  Stop.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/tmp/pip-install-d0hmj2lg/crypto-cpp-py_3ab0c761eaac4561af1b22ca8e1c1aac/setup.py", line 48, in <module>
          setup(
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/private/tmp/pip-install-d0hmj2lg/crypto-cpp-py_3ab0c761eaac4561af1b22ca8e1c1aac/setup.py", line 16, in run
          self.run_command("build_ext")
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
          _build_ext.build_ext.build_extensions(self)
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "/Users/matrix/cairo_venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/tmp/pip-install-d0hmj2lg/crypto-cpp-py_3ab0c761eaac4561af1b22ca8e1c1aac/setup.py", line 30, in build_extension
          subprocess.run(
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 524, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command './build_extension.sh' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> crypto-cpp-py

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
(cairo_venv) matrix@Judes-MacBook-Pro ~ %

**Comment by war-in** [comment]
Hi, thanks for reporting! This should close your issue #411. We are going to release a new package version with this fix today
